version: "3.8"

services:
  php-apache:
    image: php:8.1-apache
    container_name: php-apache-alert
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql-alert
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: alert_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data_alert:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-alert
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data_alert:
